site_name: StableDiffusionBook
site_description: 一个介绍 Ai 绘画的 WIKI/A WIKI about Ai painting
site_url: 'https://stable-diffusion-book.vercel.app/'
site_author: StableDiffusionBook Team
repo_url: 'https://github.com/sudoskys/StableDiffusionBook'
edit_uri: edit/main/docs/
copyright: |
  Copyright &copy; 采用 GFDL 协议

theme:
  name: material
  language: zh
  icon:
    logo: material/brush
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.sections


markdown_extensions:
  - tables
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.superfences
  - meta
  - pymdownx.tabbed:
      alternate_style: true


extra:
  social:
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/s/StableDiffusion_CN_WIKI'
    #- icom: fontawesome/brands/discord
    #  link: 'https://discord.gg/vhsArSSA6K'
  generator: true


nav:
  - 起步于此:
      - index.md
      - 新闻: GettingStarted/news.md
      - 术语: GettingStarted/term.md
      - 声明: GettingStarted/state.md
      - 贡献指南: GettingStarted/contributing.md
  - 开始之前:
      - prepare/index.md
  - 安装配置:
      - install/index.md
      - WebUi安装:
          - 运行WebUi: install/WebUi/launch.md
          - 错误处理: install/WebUi/Troubleshoot.md
  - 调试程序:
      - config/index.md
      - GPU相关: config/GPU.md
  - 绘画指南:
      - 概论:
          - paint/index.md
          - 提示工程: paint/PromptsEngineering.md
      - 工作流:
          - Txt2模式: paint/WebUi/base.md
          - Img2模式: paint/WebUi/Advanced.md
          - ControlNet: paint/WebUi/Control.md
      - 实战指南:
          - paint/Practicalguide.md
          - 评估: paint/identify.md
  - 训练模型:
      - 训练介绍: train/index.md
      - Lora 训练: train/Lora.md
      - Textual 训练: train/Textual.md
      - Hypernetwork 训练: train/Hypernetwork.md
      - DreamBooth 训练: train/DreamBooth.md
      - AestheticGradients 训练: train/AestheticGradients.md
  - 参考资料:
      - landing/index.md
      - 资料表: landing/link.md


plugins:
  - glightbox
  - search
  - social:
      cards_layout_options:
        font_family: Noto Sans SC
        color: '#D8C7B5'
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: false
          locale: en
          name: English
          nav_translations:
            AestheticGradients 训练: AestheticGradients
            DreamBooth 训练: DreamBooth
            GPU相关: Gpu Debuging
            Hypernetwork 训练: Hypernetwork
            Img2指南: Img2Guide
            Lora 训练: Lora
            NAI泄漏报告: NAI leak report
            Textual 训练: Textual Inversion
            Txt2指南: Txt2Guide
            WebUi安装: Install SDWebUi
            WebUi绘画指南: Paint With WebUi
            WebUi配置模型: Configrue Model for WebUi
            参考资料: References
            基本指南: Base guide
            声明: Statement
            安装扩展: Extension
            安装配置: Installation
            实战指南: Application Guide
            工作台: Workstations
            开始之前: Before start
            提示工程: Prompts Engineer
            新闻: News
            术语: Terminology
            概论: General
            绘画指南: Paint guide
            绘画调试: Configuration
            训练介绍: Intro
            训练模型: Train Model
            贡献指南: Contribution Guide
            资料表: Resource List
            起步于此: Start here
            运行WebUi: LaunchWebUi
            进阶指南: Advanced Guide
            鉴别: Identify
            错误处理: Troubleshoot
        - build: true
          default: true
          locale: zh
          name: 简体中文
      reconfigure_material: true
      reconfigure_search: true
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
